### ISSUE TITLE
problem adding new journal

### ISSUE THREAD

**Issue by xserra** [MTG/conferences#30]
I added a new journal call, 2019-arts.md, but it does not show. I cannot figure out what I did wrong.

**Comment by alastair** [comment]
@sarafg11 can you have a look at this?

**Comment by sarafg11** [comment]
I think it's fixed now https://github.com/MTG/conferences/pull/31. The ':' in the issue field caused it to not render propperly. I replaced it by a '-' but you can change it.

**Comment by alastair** [comment]
Great, thanks. We can also surround the text in 'quotes' to fix this.
