### ISSUE TITLE
End date for conferences

### ISSUE THREAD

**Issue by Murivan** [MTG/conferences#5]
I want to discuss the opportunity of having an end date field for conferences.
Knowing the exact length of a conference might help to plan in advance trips and ensure the availability of speakers.

**Comment by alastair** [comment]
Good idea, we can add another field to the data files. We will need a nice way of showing this data if it does or does not exist - currently the data display is a bit squashed due to the fixed width. We will look into a better way of displaying it.

**Comment by alastair** [comment]
I've added `end_date` to the template so that people can start adding it. We can decide on the way to show it if we change the template.
